version: "3.9"

services:
  python-flask:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app/
    ports:
      - "5000:5000"
    env_file:
      - .env

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - "8888:4040"
    environment:
      NGROK_PROTOCOL: tcp
      NGROK_PORT: python-flask:5000
      NGROK_AUTH: <NGROK_AUTH>
